# Visualize Fashion Image

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.cross_validation import train_test_split
from skimage import img_as_float, img_as_ubyte

/Users/prinklek/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [3]:
import skimage

In [4]:
image_path = '/Users/prinklek/Downloads/fashion-mnist_test.csv'

In [5]:
raw_img_data = pd.read_csv(image_path)

In [6]:
raw_img_data.shape

(10000, 785)

In [7]:
raw_img_data.head(10)

label  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0      0       0       0       0       0       0       0       0       9   
1      1       0       0       0       0       0       0       0       0   
2      2       0       0       0       0       0       0      14      53   
3      2       0       0       0       0       0       0       0       0   
4      3       0       0       0       0       0       0       0       0   
5      2       0       0       0       0       0      44     105      44   
6      8       0       0       0       0       0       0       0       0   
7      6       0       0       0       0       0       0       0       1   
8      5       0       0       0       0       0       0       0       0   
9      0       0       0       0       0       0       0       0       0   

   pixel9    ...     pixel775  pixel776  pixel777  pixel778  pixel779  \
0       8    ...          103        87        56         0         0   
1       0    ...           34         0         0         0         0   
2      99    ...            0         0         0         0        63   
3       0    ...          137       126       140         0       133   
4       0    ...            0         0         0         0         0   
5      10    ...          105        64        30         0         0   
6       0    ...            0         0         0         0         0   
7       0    ...          174       136       155        31         0   
8       0    ...            0         0         0         0         0   
9       0    ...           57        70        28         0         2   

   pixel780  pixel781  pixel782  pixel783  pixel784  
0         0         0         0         0         0  
1         0         0         0         0         0  
2        53        31         0         0         0  
3       224       222        56         0         0  
4         0         0         0         0         0  
5         0         0         0         0         0  
6         0         0         0         0         0  
7         1         0         0         0         0  
8         0         0         0         0         0  
9         0         0         0         0         0  

[10 rows x 785 columns]

In [8]:
raw_img_data['label'].value_counts()

7    1000
6    1000
5    1000
4    1000
3    1000
2    1000
9    1000
1    1000
8    1000
0    1000
Name: label, dtype: int64

In [ ]:
Linear0 = np.linspace(0, 1, 2500).reshape((50, 50))


print('Linear0 :', Linear0.dtype, Linear0.min(), Linear0.max())

fig, (ax0) = plt.subplots(1)
ax0.imshow(Linear0, cmap='gray')


In [9]:
df = raw_img_data[(raw_img_data['label'] == 0)|(raw_img_data['label'] == 1)]

In [10]:
df.shape

(2000, 785)

In [11]:
y = df['label'].values

In [12]:
y.shape

(2000,)

In [13]:
df.head(10)

label  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0       0       0       0       0       0       0       0       0       9   
1       1       0       0       0       0       0       0       0       0   
9       0       0       0       0       0       0       0       0       0   
23      1       0       0       0       0       0       0       0       0   
29      1       0       0       0       0       0       0       0       0   
34      1       0       0       0       0       0       0       0       0   
35      0       0       0       0       0       0       0       0       0   
38      0       0       0       0       0       0       0       0      54   
41      0       0       0       0       0       0       0       0      29   
45      0       0       0       0       0       1       0       0       0   

    pixel9    ...     pixel775  pixel776  pixel777  pixel778  pixel779  \
0        8    ...          103        87        56         0         0   
1        0    ...           34         0         0         0         0   
9        0    ...           57        70        28         0         2   
23       0    ...          227        96         0         0         0   
29       0    ...          197       177         0         0         0   
34       0    ...           70         0         0         0         0   
35      20    ...           50         0         0         0         0   
38     144    ...          115        86        11         0         0   
41     135    ...          192       201       200       194        33   
45       3    ...            0         0         0         0         0   

    pixel780  pixel781  pixel782  pixel783  pixel784  
0          0         0         0         0         0  
1          0         0         0         0         0  
9          0         0         0         0         0  
23         0         0         0         0         0  
29         0         0         0         0         0  
34         0         0         0         0         0  
35         0         0         0         0         0  
38         0         0         0         0         0  
41         0         6         1         0         0  
45         0         0         0         0         0  

[10 rows x 785 columns]

In [14]:
X = df[df.columns[1:]].iloc[:].values

In [15]:
X.shape

(2000, 784)

In [16]:
from sklearn.cross_validation import train_test_split
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5)

In [66]:
X_train[:5]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [68]:
y_train[:5]

array([0, 0, 0, 0, 1])

In [17]:
from skimage import feature
feat_df = pd.DataFrame(np.empty((X_train.shape[0],81)))
for idx, row in enumerate(X_train):
    a = row.reshape(28, 28)
    X_feat = skimage.feature.hog(a)
    feat_df.iloc[idx,:] = X_feat
    

/Users/prinklek/anaconda3/lib/python3.6/site-packages/skimage/feature/_hog.py:119: skimage_deprecation: Default value of `block_norm`==`L1` is deprecated and will be changed to `L2-Hys` in v0.15
  'be changed to `L2-Hys` in v0.15', skimage_deprecation)


In [18]:
feat_df.tail()

0         1         2         3         4         5         6   \
995  0.033582  0.036818  0.029199  0.014657  0.011814  0.000000  0.004893   
996  0.026789  0.021845  0.041566  0.000267  0.013878  0.000000  0.001056   
997  0.022441  0.010916  0.020764  0.004052  0.006477  0.001918  0.001296   
998  0.012872  0.007502  0.031669  0.004428  0.014529  0.001505  0.010411   
999  0.017198  0.021753  0.052834  0.006972  0.012500  0.001565  0.005984   

           7         8         9     ...           71        72        73  \
995  0.001752  0.005750  0.002076    ...     0.023860  0.052435  0.001248   
996  0.000000  0.006889  0.018064    ...     0.001403  0.020644  0.000817   
997  0.001173  0.004466  0.013405    ...     0.009936  0.024440  0.008030   
998  0.001578  0.013492  0.001772    ...     0.004498  0.017910  0.000236   
999  0.008485  0.001847  0.013909    ...     0.018132  0.030352  0.000681   

           74        75        76        77        78        79        80  
995  0.000428  0.001353  0.000853  0.001000  0.003437  0.005787  0.062353  
996  0.000917  0.000678  0.001425  0.001469  0.000877  0.024928  0.042499  
997  0.000000  0.000813  0.006633  0.007275  0.011820  0.031928  0.043561  
998  0.000115  0.000091  0.000487  0.000386  0.000688  0.000146  0.011398  
999  0.001166  0.001031  0.000073  0.000432  0.000155  0.004186  0.045642  

[5 rows x 81 columns]

In [19]:
feat_df.shape

(1000, 81)

In [ ]:
#X = df[df.columns[1:]].iloc[0,:].values.reshape(28,28)

In [ ]:
df.columns[1:]

In [ ]:
df[df.columns[1:]]

In [ ]:
df[df.columns[1:]].iloc[0,:]

In [ ]:
df[df.columns[1:]].iloc[0,:].values

In [20]:
X.shape

(2000, 784)

In [21]:
df[df.columns[1:]].iloc[0,:].values.reshape(28,28)

array([[  0,   0,   0,   0,   0,   0,   0,   9,   8,   0,   0,  34,  29,
          7,   0,  11,  24,   0,   0,   3,   3,   1,   0,   1,   1,   0,
          0,   0],
       [  0,   0,   4,   0,   0,   1,   0,   0,   0,   0,   0,  44,  88,
         99, 122, 123,  80,   0,   0,   0,   0,   1,   1,   1,   0,   0,
          0,   0],
       [  0,   0,   1,   2,   0,   0,   0,   3,  46, 174, 249,  67,   0,
         94, 210,  61,  14, 212, 157,  37,   0,   0,   0,   0,   1,   0,
          0,   0],
       [  0,   0,   2,   2,   0,  23, 168, 206, 242, 239, 238, 214, 125,
         61, 113,  74, 133, 236, 238, 236, 203, 184,  20,   0,   1,   0,
          0,   0],
       [  0,   0,   1,   0,   0, 175, 245, 223, 207, 205, 206, 216, 255,
        237, 251, 232, 223, 212, 200, 205, 216, 249, 173,   0,   0,   2,
          0,   0],
       [  0,   0,   7,   0,  53, 225, 201, 197, 200, 201, 206, 199, 197,
        185, 194, 204, 232, 226, 249, 219, 194, 205, 229,  33,   0,   1,
          0,   0],
       [  

Split here on the actual data frame

In [ ]:
target = df['label'] 
pixel_values = df[df.columns[1:]]

In [ ]:
I1 = pixel_values.iloc[0,:].values.reshape(28, 28)

In [ ]:
print(I1)

In [ ]:
print("Shape:", I1.shape)
print("Values min/max:", I1.min(), I1.max())

plt.imshow(I1, interpolation='nearest');

In [ ]:
fig, (ax_jet, ax_gray) = plt.subplots(ncols=2, figsize=(10, 5))

ax_jet.imshow(I1, cmap='jet')
ax_gray.imshow(I1, cmap='gray')

In [ ]:
upper_shirt = I1[5:10 ]

In [ ]:
fig, (ax_jet, ax_gray) = plt.subplots(ncols=2)
ax_jet.imshow(upper_shirt, cmap='jet')
ax_gray.imshow(upper_shirt, cmap='gray')

In [ ]:
I2 = pixel_values.iloc[1,:].values.reshape(28,28)

In [ ]:
print("Shape:", I2.shape)
print("Values min/max:", I1.min(), I1.max())

plt.imshow(I2, interpolation='nearest', cmap='gray');

In [ ]:
from skimage import img_as_float, img_as_ubyte

image = I1

image_float = img_as_float(image)
image_ubyte = img_as_ubyte(image)

print("type, min, max:", image_float.dtype, image_float.min(), image_float.max())
print("type, min, max:", image_ubyte.dtype, image_ubyte.min(), image_ubyte.max())

#print("231/255 =", 231/255.)

In [ ]:
#MEAN KERNEL FILETERING

In [ ]:
mean_kernel = 1.0/9.0 * np.ones((3, 3))

print(mean_kernel)

In [ ]:
from scipy.ndimage import convolve

%precision 2
print(I1)
print(convolve(I1, mean_kernel))

In [ ]:
## GAUSSIAN FILTER

In [ ]:
from skimage import filters

smooth_mean = convolve(I1, mean_kernel)
sigma = 1
smooth = filters.gaussian(I1, sigma)
plt.imshow(I1, cmap='gray');
#plt.imshow(I1, interpolation='nearest');

In [ ]:
plt.imshow(smooth_mean, cmap='gray')

In [ ]:
plt.imshow(smooth, cmap='gray')

In [ ]:
I2 = pixel_values.iloc[1,:].values.reshape(28,28)

In [ ]:
from skimage import color
from scipy import ndimage as ndi

In [ ]:
mean_diff = ndi.convolve([0., 0, 1, 0, -1, 0, 0], [1/3, 1/3, 1/3])
print(mean_diff)

In [ ]:
# SEGMENTATION WITH FILTERS

In [ ]:
from skimage import filters
edges = filters.sobel(I1)
plt.imshow(edges, cmap='gray')


In [ ]:
from skimage.morphology import watershed
from scipy import ndimage as ndi

In [ ]:
threshold = filters.threshold_otsu(edges)
print(threshold)
# Euclidean distance transform
# How far do we have to travel from a non-edge to find an edge?
non_edges = (edges < threshold)
plt.imshow(non_edges)

In [ ]:
distance_from_edge = ndi.distance_transform_edt(non_edges)

plt.imshow(distance_from_edge, cmap='viridis');
plt.colorbar()

In [ ]:
from skimage import feature
peaks = feature.peak_local_max(distance_from_edge)
print("Peaks shape:", peaks.shape)

In [ ]:
plt.imshow(edges, cmap='gray')
plt.plot(peaks[:, 1], peaks[:, 0], 'ro');
plt.axis('image')

In [ ]:
peaks_image = np.zeros(I1.shape, np.bool)
peaks_image[tuple(np.transpose(peaks))] = True
seeds, num_seeds = ndi.label(peaks_image)

In [ ]:
plt.imshow(peaks_image)

In [ ]:
plt.imshow(seeds, cmap='gray')


In [ ]:
ws = watershed(edges, seeds)

from skimage import color
plt.imshow(color.label2rgb(ws, I1));

In [ ]:
from skimage.future import graph

In [ ]:
g = graph.rag_boundary(ws, edges)

In [ ]:
plt.imshow(ws == 20)
print(g[20])

In [22]:
from skimage import feature

In [23]:
X_feat = skimage.feature.hog(I1)

NameError: name 'I1' is not defined

In [24]:
X_feat

array([  1.71979336e-02,   2.17527040e-02,   5.28336445e-02,
         6.97249169e-03,   1.25004575e-02,   1.56482985e-03,
         5.98407838e-03,   8.48533728e-03,   1.84656879e-03,
         1.39093307e-02,   2.10284275e-02,   9.14228359e-03,
         3.17786589e-02,   3.92324116e-02,   9.29390925e-03,
         1.64958176e-02,   2.17253801e-02,   2.23683347e-02,
         9.26044142e-03,   7.58951480e-03,   7.84051873e-03,
         1.23143907e-02,   2.77394020e-02,   1.66149565e-02,
         1.94838547e-02,   2.02562309e-03,   1.85655657e-03,
         2.34852756e-02,   7.61502600e-03,   0.00000000e+00,
         1.66966535e-03,   1.56633394e-02,   7.29541943e-03,
         3.70156540e-02,   2.84583075e-02,   3.64662814e-02,
         1.94748361e-02,   9.94637524e-03,   2.82010452e-03,
         3.00669730e-03,   2.79543408e-03,   3.45896524e-03,
         2.63885401e-03,   1.02642518e-02,   1.14339697e-02,
         3.55466304e-02,   1.20564927e-02,   4.00102408e-03,
         1.14032259e-02,

In [25]:
X_feat.shape

(81,)

In [26]:
y_train.shape

(1000,)

In [ ]:
#from sklearn import svm
#clf = svm.SVC(C=100, kernel='rbf', gamma='auto')

In [ ]:
#clf.fit(X_feat,y_train)

In [ ]:
#clf.predict(X_train)

In [27]:
from sklearn import linear_model
lr = linear_model.LinearRegression()
lr.fit(feat_df, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [28]:
lr.score(feat_df, y_train)

0.91912795229397526

In [29]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ..., 
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [31]:
from sklearn import linear_model
logr = linear_model.LogisticRegression()


In [32]:
logr.fit(feat_df, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [33]:
logr.score(feat_df, y_train)

0.96899999999999997

In [34]:
logr.score()

TypeError: score() missing 2 required positional arguments: 'X' and 'y'

In [35]:
X_test[:5]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [36]:
y_test[:5]

array([1, 1, 0, 1, 1])

In [37]:
from skimage import feature
XTfeat_df = pd.DataFrame(np.empty((X_test.shape[0],81)))
for idx, row in enumerate(X_test):
    b = row.reshape(28, 28)
    XT_feat = skimage.feature.hog(b)
    XTfeat_df.iloc[idx,:] = XT_feat
    

/Users/prinklek/anaconda3/lib/python3.6/site-packages/skimage/feature/_hog.py:119: skimage_deprecation: Default value of `block_norm`==`L1` is deprecated and will be changed to `L2-Hys` in v0.15
  'be changed to `L2-Hys` in v0.15', skimage_deprecation)


In [38]:
XT_feat[:28]

array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.08615338,
        0.00737007,  0.00065168,  0.00061434,  0.02897152,  0.00690662,
        0.00237076,  0.00775023,  0.00858289,  0.05012393,  0.00064801,
        0.00069316,  0.00766927,  0.00299693,  0.        ,  0.00105427,
        0.03529581,  0.01832911,  0.        ])

In [49]:
yhat = logr.predict(XTfeat_df)

In [50]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [52]:
print(classification_report(y_test,yhat))

             precision    recall  f1-score   support

          0       0.00      0.00      0.00       481
          1       0.47      0.82      0.60       519

avg / total       0.24      0.42      0.31      1000



In [53]:
print(confusion_matrix(y_test,yhat,labels=[0,1]))

[[  0 481]
 [ 95 424]]


In [39]:
XTfeat_df.head(10)

0         1         2         3         4         5         6   \
0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
1  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
2  0.040112  0.017786  0.030046  0.012071  0.003753  0.000571  0.000000   
3  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
4  0.010835  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
5  0.017844  0.030045  0.026265  0.000404  0.008563  0.000905  0.000310   
6  0.025139  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
7  0.035205  0.022751  0.027200  0.007570  0.010161  0.002512  0.000645   
8  0.066454  0.015269  0.000000  0.000000  0.000000  0.000000  0.000000   
9  0.037649  0.019546  0.024058  0.012004  0.012803  0.001620  0.007593   

         7         8         9     ...           71        72        73  \
0  0.000000  0.000000  0.072662    ...     0.161844  0.124409  0.000000   
1  0.000000  0.000000  0.061387    ...     0.081184  0.053660  0.000632   
2  0.000000  0.005832  0.009462    ...     0.022188  0.020877  0.001225   
3  0.000000  0.000000  0.079084    ...     0.057369  0.023571  0.000000   
4  0.000000  0.000000  0.050989    ...     0.078178  0.026544  0.001010   
5  0.000369  0.004617  0.002385    ...     0.004724  0.053586  0.011348   
6  0.000000  0.000000  0.012186    ...     0.051674  0.053492  0.002507   
7  0.000000  0.001550  0.002095    ...     0.017937  0.025679  0.003410   
8  0.000000  0.012244  0.007526    ...     0.066282  0.093637  0.001400   
9  0.000000  0.006920  0.003504    ...     0.042358  0.045249  0.001731   

         74        75        76        77        78        79        80  
0  0.000000  0.000000  0.000580  0.000000  0.001757  0.000000  0.021233  
1  0.003796  0.003974  0.006703  0.030903  0.005572  0.007921  0.044647  
2  0.000526  0.000265  0.000341  0.000196  0.001022  0.000750  0.094453  
3  0.000000  0.000938  0.000000  0.000000  0.008194  0.010442  0.050189  
4  0.000000  0.000076  0.000072  0.000000  0.000000  0.000582  0.085316  
5  0.012841  0.017755  0.002287  0.001258  0.000703  0.000000  0.028718  
6  0.000000  0.003226  0.000000  0.000000  0.003882  0.003800  0.029550  
7  0.000472  0.009523  0.007816  0.001619  0.009368  0.019023  0.052730  
8  0.001017  0.000545  0.000000  0.000000  0.001308  0.002402  0.010610  
9  0.001866  0.000327  0.000622  0.000540  0.000000  0.002066  0.059983  

[10 rows x 81 columns]

In [40]:
from sklearn import linear_model
lr = linear_model.LinearRegression()
lr.fit(XTfeat_df, y_test)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [41]:
lr.score(XTfeat_df, y_test)

0.92368670227315985

In [43]:
lr.fit(feat_df, y_test)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [45]:
lr.score(feat_df, y_test)

0.094757486914571309

In [50]:
from sklearn import linear_model
logr = linear_model.LogisticRegression()
logr.fit(XTfeat_df, y_test)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [46]:
logr.score(XTfeat_df, y_test)

0.96699999999999997

In [47]:
logr.fit(feat_df, y_test)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [48]:
logr.score(feat_df, y_test)

0.54600000000000004